-- DONG_MAY
CREATE TABLE [dbo].[DONG_MAY](
	[Ma_dong_may] [varchar](50) NOT NULL,
	[Ten_dong_may] [nvarchar](36) NOT NULL,
	[Dung_luong_pin] [nvarchar](63) NOT NULL,
	[Kich_thuoc] [nvarchar](63) NOT NULL,
	[Mo_ta] [nvarchar](63) NULL,
 CONSTRAINT [PK__DONG_MAY__A3D7C1A3DD33B750] PRIMARY KEY CLUSTERED 
(
	[Ma_dong_may] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

-- DIEN_THOAI
CREATE TABLE [dbo].[DIEN_THOAI](
	[Ma_Imei] [varchar](50) NOT NULL,
	[Hinh_anh] [image] NULL,
	[Mau_sac] [nvarchar](18) NULL,
	[Trang_thai] [nvarchar](18) NULL,
	[Gia_nhap] [numeric](18, 2) NULL,
	[Gia_ban] [numeric](18, 2) NULL,
	[Thue] [numeric](4, 2) NULL,
	[Ma_dong_may] [varchar](50) NOT NULL,
 CONSTRAINT [PK__DIEN_THO__0329CF7905FB7BA9] PRIMARY KEY CLUSTERED 
(
	[Ma_Imei] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

-- CT_DON_BAN
CREATE TABLE [dbo].[CT_DON_BAN](
	[Ma_Imei] [varchar](50) NOT NULL,
	[Ma_don_ban] [varchar](50) NOT NULL,
 CONSTRAINT [PK__CT_DON_B__1E0B7D4C4B3ADAA6] PRIMARY KEY CLUSTERED 
(
	[Ma_Imei] ASC,
	[Ma_don_ban] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

-- DON_BAN
CREATE TABLE [dbo].[DON_BAN](
	[Ma_don_ban] [varchar](50) NOT NULL,
	[Ngay_tao_don] [date] NULL,
	[Gio_tao_don] [time](0) NULL,
	[SL_dien_thoai] [int] NULL,
	[Tri_gia] [numeric](18, 2) NULL,
	[So_tien_tra] [numeric](18, 2) NULL,
	[Trang_thai] [nvarchar](50) NULL,
	[Ma_khach_hang] [varchar](50) NOT NULL,
	[Ma_nhan_vien] [varchar](50) NULL,
	[Ma_khuyen_mai] [varchar](50) NULL,
 CONSTRAINT [PK__DON_BAN__D22B2350A2DEBDCA] PRIMARY KEY CLUSTERED 
(
	[Ma_don_ban] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

-- CT_DON_NHAP
CREATE TABLE [dbo].[CT_DON_NHAP](
	[Ma_Imei] [varchar](50) NOT NULL,
	[Ma_don_nhap] [varchar](50) NOT NULL,
 CONSTRAINT [PK__CT_DON_N__5CCA52F4EDF37E40] PRIMARY KEY CLUSTERED 
(
	[Ma_Imei] ASC,
	[Ma_don_nhap] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

-- DON_NHAP
CREATE TABLE [dbo].[DON_NHAP](
	[Ma_don_nhap] [varchar](50) NOT NULL,
	[Ngay_nhap] [date] NULL,
	[Gio_nhap] [time](0) NULL,
	[SL_dien_thoai] [int] NULL,
	[Tri_gia] [numeric](18, 2) NULL,
	[Ma_NCC] [varchar](50) NOT NULL,
	[Ma_nhan_vien] [varchar](50) NULL,
 CONSTRAINT [PK__DON_NHAP__FE39D8D404BE1382] PRIMARY KEY CLUSTERED 
(
	[Ma_don_nhap] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

-- GHI_NO
CREATE TABLE [dbo].[GHI_NO](
	[STT_ghi_no] [int] NOT NULL,
	[Ma_khach_hang] [varchar](50) NOT NULL,
	[Ngay_ghi_no] [date] NULL,
	[Chua_thanh_toan] [numeric](18, 2) NOT NULL,
 CONSTRAINT [PK__GHI_NO__DEBB94B09423D4CC] PRIMARY KEY CLUSTERED 
(
	[STT_ghi_no] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

-- NHA_CUNG_CAP
CREATE TABLE [dbo].[NHA_CUNG_CAP](
	[Ma_NCC] [varchar](50) NOT NULL,
	[Ten_NCC] [nvarchar](36) NOT NULL,
	[Dia_chi] [nvarchar](63) NOT NULL,
	[SDT] [varchar](18) NULL,
 CONSTRAINT [PK__NHA_CUNG__C23A87C78AC23BBA] PRIMARY KEY CLUSTERED 
(
	[Ma_NCC] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

-- NHAN_VIEN
CREATE TABLE [dbo].[NHAN_VIEN](
	[Ma_nhan_vien] [varchar](50) NOT NULL,
	[Mat_khau] [varchar](27) NOT NULL,
	[Ten_nhan_vien] [nvarchar](36) NOT NULL,
	[Chuc_vu] [nvarchar](36) NULL,
	[Gmail] [varchar](36) NULL,
	[SDT] [varchar](18) NULL,
 CONSTRAINT [PK__NHAN_VIE__7567117FF3298FD4] PRIMARY KEY CLUSTERED 
(
	[Ma_nhan_vien] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

-- KHACH_HANG
CREATE TABLE [dbo].[KHACH_HANG](
	[Ma_khach_hang] [varchar](50) NOT NULL,
	[SDT] [varchar](18) NOT NULL,
	[Ten_khach_hang] [nvarchar](36) NULL,
	[Dia_chi] [nvarchar](63) NULL,
	[Gmail] [varchar](36) NULL,
 CONSTRAINT [PK__KHACH_HA__F9279E9636D6B3B3] PRIMARY KEY CLUSTERED 
(
	[Ma_khach_hang] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

-- KHUYEN_MAI
CREATE TABLE [dbo].[KHUYEN_MAI](
	[Ma_khuyen_mai] [varchar](50) NOT NULL,
	[Ten_chuong_trinh] [nvarchar](36) NOT NULL,
	[Chiet_khau] [numeric](4, 2) NULL,
	[SL_ap_dung] [int] NULL,
	[Ngay_ap_dung] [date] NULL,
	[Ngay_ket_thuc] [date] NULL,
 CONSTRAINT [PK__KHUYEN_M__19AF70725F8B972C] PRIMARY KEY CLUSTERED 
(
	[Ma_khuyen_mai] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

-- ADMIN
CREATE TABLE [dbo].[ADMIN](
	[Ten_dang_nhap] [varchar](36) NOT NULL,
	[Mat_khau] [varchar](27) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Ten_dang_nhap] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

-- THONG_KE_NGAY
CREATE TABLE [dbo].[THONG_KE_NGAY](
	[Ngay_thong_ke] [date] NOT NULL,
	[So_luong_ban] [int] NULL,
	[Tong_thu] [numeric](18, 2) NULL,
PRIMARY KEY CLUSTERED 
(
	[Ngay_thong_ke] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO